version: '3.9'

x-env: &env

  POSTGRES_PASSWORD: &db_password '${DB_PASSWORD}'
  POSTGRES_USER: &db_username '${DB_USERNAME}'
  POSTGRES_DB: &db_name '${DB_NAME}'

services:

  postgres:

    container_name: postgres_container

    image: postgres:latest

    environment: *env
    
    volumes:
      - type: volume
        source: db_volume
        target: /var/lib/postgresql/data
    
    ports:
      - "5432:5432"
      
    restart: &restartpolicy unless-stopped

  app:
  
    container_name: application_container
    
    build: 
      context: .
      args:
        POETRY_VERSION: "${POETRY_VERSION}"
        TYPE_PROJECT_ENV: "${TYPE_PROJECT_ENV}"

    environment:

      DB_HOST: 'postgres'
      DB_PORT: '5432'
      DB_PASSWORD: *db_password
      DB_USERNAME: *db_username
      DB_NAME: *db_name
      DB_DIALECT: "${DB_DIALECT}"
    
      SMTP_ADDRESS: "${SMTP_ADDRESS}"
      SMTP_PORT: "${SMTP_PORT}"
      SMTP_EMAIL: "${SMTP_EMAIL}"
      SMTP_PASSWORD: "$SMTP_PASSWORD"

      SUPER_USER_EMAIL: "${SUPER_USER_EMAIL}"
      SUPER_USER_PASSWORD: "${SUPER_USER_PASSWORD}"    
    
    command: "uvicorn car_indicators.main:app --host 0.0.0.0 --port 8000"

    depends_on:
      - postgres

    ports:
      - "8000:8000"

volumes:
  db_volume: